version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8000
    networks:
      - app-network

  database:
    image: mysql:8
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: some-root-password
      MYSQL_DATABASE: comp1682
      MYSQL_USER: user_app
      MYSQL_PASSWORD: pwd_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
